server:
  port: 8080
spring:
  application:
    name: myspringcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/011010110/myspringcloud
          username: 582966876@qq.com
          password: lilinhua911
          search-paths: springcloud-config/src/main/resources/config
