spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: lilinhua911
    driver-class-name: com.mysql.cj.jdbc.Driver