
spring:
  jpa:
    generate-ddl: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: lilinhua911
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: springcloud-provider-hello
server:
  port: 8083
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka #注册中心地址
info:
  company.name: org.jiang
  company.address: 四川成都
  description: hello-consumer
